<a href="https://colab.research.google.com/github/jmhuertasg/ML_21_Days/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Manipulacion de Numpy

Instalacion NUMPY

In [ ]:
pip install numpy

Import Numpy in program


In [ ]:
import numpy as pn

Create Vector

In [ ]:
#Load Library
import numpy as np

#Create a row vector
row_vector = np.array([10,15,20])

#Create a column vector
column_vector =np.array([[10],[20],[30]])
print(column_vector)

[[10]
 [20]
 [30]]


Create Matrix

In [ ]:
#Create a Matrix
matrix =np.array([[10,20,30],[40,50,60]])
print(matrix)

[[10 20 30]
 [40 50 60]]


Accessing Elements

In [ ]:
#Create a vector as a Row
row_vector = np.array([10,20,30,40,50,60])
print("row_vector",row_vector)

#Create a Matrix
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])

#Select 2nd element of Vactor
print("Matrix:",row_vector[1])

#Select 

Matrix

In [ ]:
#Create a Matrix
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])

#View the number of rows and Columns
print("Rows and Column",matrix.shape)

#View the number of elements (rows*columns)
print("Total Elements",matrix.size)

#View the number of Dimensions(2 in the case)
print("Dimension",matrix.ndim)

In [ ]:
p