<a href="https://colab.research.google.com/github/jmhuertasg/ML_21_Days/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Manipulacion de Numpy

Instalacion NUMPY

In [ ]:
pip install numpy

Import Numpy in program


In [ ]:
import numpy as pn

Create Vector

In [ ]:
#Load Library
import numpy as np

#Create a row vector
row_vector = np.array([10,15,20])

#Create a column vector
column_vector =np.array([[10],[20],[30]])
print(column_vector)

[[10]
 [20]
 [30]]


Create Matrix

In [ ]:
#Create a Matrix
matrix =np.array([[10,20,30],[40,50,60]])
print(matrix)

[[10 20 30]
 [40 50 60]]


Accessing Elements

In [ ]:
#Create a vector as a Row
row_vector = np.array([10,20,30,40,50,60])
print("row_vector",row_vector)

#Create a Matrix
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])

#Select 2nd element of Vactor
print("Matrix:",row_vector[1])

#Select 

row_vector [10 20 30 40 50 60]
Matrix: 20


Matrix

In [ ]:
#Create a Matrix
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])

#View the number of rows and Columns
print("Rows and Column",matrix.shape)

#View the number of elements (rows*columns)
print("Total Elements",matrix.size)

#View the number of Dimensions(2 in the case)
print("Dimension",matrix.ndim)

Rows and Column (3, 3)
Total Elements 9
Dimension 2


Min and Max

In [ ]:
#Create a Matrix
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])

#Return the max element
print(np.max(matrix))

#Return the min element
print(np.min(matrix))

#To find the max element in each column
print(np.max(matrix,axis=0))

#To find the max element in each row_vector
print(np.max(matrix,axis=1))

90
10
[70 80 90]
[30 60 90]


In [11]:
#Create a Matrix
matrix =np.array([[10,20,30],[40,50,60],[70,80,90]])

#Reshape
print(matrix.reshape(9,-1))

#Here -1 says as many columns as needed and 1 row
print(matrix.reshape(1,-1))

#If we provide only 1 value Reshape would return a 1-d array
print(matrix.reshape(9))

#We can also use the Flatten method to convet a matrix to 1-d array
print(matrix.flatten)


[[10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]]
[[10 20 30 40 50 60 70 80 90]]
[10 20 30 40 50 60 70 80 90]
<built-in method flatten of numpy.ndarray object at 0x7fdbad2c4120>
